### ISSUE TITLE
Error: File not found "losses/vgg16_lpips.pt" used in lpips.py

### ISSUE THREAD

**Issue by anureetchhabra** [oppo-us-research/FA-VAE#1]

**Comment by wang5019** [comment]
download from https://github.com/richzhang/PerceptualSimilarity/blob/master/lpips/weights/v0.0/vgg.pth
change losses/lpips.py  line 79   vgg = models.vgg16(pretrained=True)

**Comment by xinmiaolin** [comment]
Hi, is this issue still relevant?

**Comment by anureetchhabra** [comment]
Hi, thanks for the reply, this issue was resolved with the link you
provided.

**Comment by 649459021** [comment]
Hi,  where can I download this vgg checkpoint?

**Comment by 649459021** [comment]
@xinmiaolin

**Comment by xinmiaolin** [comment]
Hi,

The LPIPS details can be referred here: https://github.com/richzhang/PerceptualSimilarity
