### ISSUE TITLE
sigma

### ISSUE THREAD

**Issue by zhenyuan1234** [oppo-us-research/FA-VAE#2]
Hi, where is the update process of learnable sigma in the code? Thanks！

**Comment by xinmiaolin** [comment]
Hi,

The sigmas are first initialized with the FA-VAE, i.e. https://github.com/oppo-us-research/FA-VAE/blob/1b26643f4a99fae5c17e1690c2fbd9256313534f/models/vqgan_fcm.py#L67

Then, during the training process, it is updated alongside the model's parameters, i.e. https://github.com/oppo-us-research/FA-VAE/blob/1b26643f4a99fae5c17e1690c2fbd9256313534f/favae_scripts/train_favae.py#L102

Hope this helps!
